# Versi Docker Compose yang digunakan
version: '2.2.3'

# Membuat dua buah service: item-app dan item-db
services:
  item-app:
    # Menggunakan image item-app dari GitHub Packages
    image: ghcr.io/emresutisna/item-app:v1
    # Melakukan port mapping agar dapat diakses dari port 80 di host
    ports:
      - 80:8080
    # Menerapkan restart policy agar container selalu restart ketika terhenti
    restart: always
    # hanya berjalan setelah item-db diluncurkan
    depends_on:
      - item-db

  item-db:
    # Menggunakan image mongo:3 dari Docker Hub
    image: mongo:3
    # Menerapkan restart policy agar container selalu restart ketika terhenti    
    restart: always
    # Memakai volume bernama app-db dengan target /data/db di container
    volumes:
      - app-db:/data/db

# Membuat volume bernama app-db
volumes:
  app-db:
